<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Filter" Id="{f84eb359-70db-4fa7-ad62-5d2e7ab4d13e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Filter
VAR_INPUT
	:=	rInRaw/Livelli*(Vmax-Vmin)/2.0;
END_VAR
VAR_OUTPUT
	
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Filter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>