<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Sensor" Id="{9fa85518-2ab9-47fc-a442-bf72b57e6579}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR_IN_OUT
	stColors : ST_CSL_Colors;
	stIn : ST_CSL_In;
	stOut : ST_CSL_Out;
	stParams
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Sensor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>