<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Processing" Id="{e6c1c698-a5ab-41a3-a94f-e6ef9684c89a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Processing
VAR_INPUT
	SensorInput	:	REAL;
END_VAR
VAR_OUTPUT
	
END_VAR
VAR_IN_OUT
	slot		:	INT;	
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Processing">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>