<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Selettore_Colori" Id="{5352a273-edff-4dd4-83d4-c79be356614d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Selettore_Colori
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Selettore_Colori">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>